openstack-k8s-operators/openstack-must-gather

- Dockerfile
- Makefile
- README.md
- collection-scripts/common.sh
- collection-scripts/gather
- collection-scripts/gather_apiservices
- collection-scripts/gather_crds
- collection-scripts/gather_crs
- collection-scripts/gather_ctlplane_resources
- collection-scripts/gather_network
- collection-scripts/gather_services_cm
- collection-scripts/gather_services_status
- collection-scripts/gather_sub
- collection-scripts/gather_webhooks
This patch represent the bootstrap of the must-gather project.
It provides a firs base collection of scripts required in the `NextGen` context.
Starting from the work already done in the director operator [1], the idea is
to collect all the resources required to ease `OpenStack` services troubleshooting
in the `OpenShift` context.
Follow up patch:
- gather secrets and mask/obfuscate sensitive data
> Bootstrap must-gather project

- collection-scripts/gather
- collection-scripts/gather_secrets
This patch introduces the ability to gather secrets for the available namespaces.
We're limiting secrets gather only to the defined OpenStack services, because some components like nova and cinder encode the whole config file in a secrets and don't rely anymore on the initContainer.
We're going to apply masking and obfuscation, as well as improving the gathering flow in a follow up patch.
> Gather secrets for targeted OSP services

- README.md
- collection-scripts/common.sh
- collection-scripts/gather
- collection-scripts/gather_services_status
This patch improves the way we're gathering information from the existing ctlplane services. In particular, for each service it's possible to define an entry in the `get_status()` `switch/case` and point to the implemented service function. As an example, this patch introduces the same commands we're running for neutron through `SOS` reports [1]. 
The output is stored within the `ctlplane/<service>` directory generated by the must-gather tool.
[1] https://github.com/sosreport/sos/blob/main/sos/report/plugins/openstack_neutron.py#L57-L64
> Get neutron status from the existing ctlplane

- collection-scripts/common.sh
- collection-scripts/gather
- collection-scripts/gather_apiservices
- collection-scripts/gather_crs
- collection-scripts/gather_ctlplane_resources
This patch introduces a new, generic function to be able to expand the existing `NAMESPACES` related array with an arbitrary number of elements that reflect a certain criteria. In particular, the gather script adds a new line to grow the existing array adding every project that matches with `kuttl`: by doing this we can finally run the regular resource gathering against this set of additional namespaces.
> Gather data from kuttl namespaces

- README.md
This patch improves the last `README` section by documenting how multiple `imagestreams` can be combined in a single command to `gather` information about multiple features.
> Document how image-stream can be combined in a single command

- README.md
The current instructions in the README.md file are referencing to the `must-gather` image, which is the wrong one since it's for Director Operator deployments.
This patch fixes this and uses the right name, `openstack-must-gather`
> README: Change image name

- Dockerfile
- README.md
- collection-scripts/gather
- collection-scripts/gather_ctlplane_resources
- collection-scripts/gather_debug
- collection-scripts/gather_run
This PR includes several improvements:
- Return the output of the must-gather run into the files as `run.log`
- Add and document a debug mode
- Have per container logs
- Rename `<pod>-describe.log` to `<pod>-describe`
> General Improvements

- collection-scripts/common.sh
- collection-scripts/gather_nodes
- collection-scripts/gather_run
This patch adds a `gather_nodes` script that is supposed to inspect the `openshift nodes` resource and dump some useful information. The script can be extended with follow up patches to gather more than just the nodes resources.
> Get nodes resources from the current OCP deployment

- .github/workflows/sanity-check.yaml
- Makefile
This patch adds a basic github action that can be used to gate patches and perform at least a sanity-check until some CI jobs (Prow based) are setup.
> Add basic github action to perform sanity-check against PRs

- collection-scripts/gather_crs
I _think_ we're missing `BareMetalHost`s in the gathered CRs, but perhaps we already do this elsewhere.  Anyhow, proposing this just in case.
> Collect Metal3 BareMetalHost CRs

- OWNERS
- OWNERS_ALIASES
The repo containing the configuration for the Tide auto merging bot reads the owners file in this repository to set who can modify the config after the initial configuration.
> Add owners file to be used by tide

- collection-scripts/gather_apiservices
- collection-scripts/gather_crds
- collection-scripts/gather_crs
This patch fixes in the first place the usage of the `resources` variable.
The purpose of this variable is to define a set of `k8s` related services
that should be collected for each `namespace`; for this reason it's
defined in `common.sh` and exported, so it can be used in any script
that is sourced by `gather_run`.
Instead of using the same `$resources` variable that is used a lot in the
collection-scripts, this change customizes the variable name used to collect
`CR(s)` and `apiservices`, and it avoids collisions with other `get_resources`
happening in other `namespaces`.
In addition, this patch fixes the way `CRD(s)` are collected: they are global
and shouldn't be collected `per-namespace`, hence they're now collected
within the `crd/` folder created in the root `must-gather` …
> Do not redefine the global $resources variable

- Dockerfile
- README.md
- collection-scripts/gather_edpm_sos
- collection-scripts/gather_run
This patch adds a mechanism to gather SOS reports from EDPM nodes.
Unlike the SOS of controller nodes, this mechanism is disabled by default so that openstack-must-gather doesn't generate SOS reports for any EDPM node.
Using environmental variable `SOS_EDPM` we can request gathering SOS reports for all or specific EDPM nodes:
- `SOS_EDPM=all` ==> Gathers SOS reports for ALL nodes. Useful for CI and testing.
- `SOS_EDPM=edpm-compute-0,edpm-compute-1` ==> Gathers SOS reports for those 2 sepecific nodes. Useful for example for issues with live migration.
Just like the SOS gathering of controller nodes, the SOS reports are stored uncompressed in the must-gathere report to facilitate analysis.
This patch assumes there's connectivity between the debug container and the EDPM nodes, which at …
> Add SOS report of EDPM nodes

- collection-scripts/gather_services_status
Implements: https://issues.redhat.com/browse/OSPRH-730
> Nova and Placement specific information gathering

- collection-scripts/gather_edpm_sos
- collection-scripts/gather_sos
This patch adds a `tee` command to the download and decompression pipe in the gather_sos script. By writing the output of cat and the input of tar into a file we can see what it got on failure.
> Temporary debugging for SOS gathering

- zuul.d/projects.yaml
This patch replaces the noop job with a real job that deploys
a real environment with a fresh openstack-must-gather image after
https://github.com/openstack-k8s-operators/ci-framework/pull/868 merges
> Add podified-multinode-edpm-deployment-crc zuul job

- collection-scripts/common.sh
- collection-scripts/gather_run
This patch adds the ability to pass `ADDITIONAL_NAMESPACES` when the gather command is invoked. The approach is consistent with what already done with `sos reports` gathering.
> Pass ADDITIONAL_NAMESPACES when must-gathering is invoked

- README.md
- collection-scripts/gather_edpm_sos
This patch adds the ability to pass additional sos report plugins
using the environment variable SOS_EDPM_PLUGINS. Due to [1] not being
released yet, I have added the plugins it would include and as such
should be removed when [1] is released. A todo has been added to make
this clear.
[1] https://github.com/openstack-k8s-operators/openstack-must-gather/pull/18
> Add ability to provide list of sos plugins to openstack-must-gather

- README.md
- collection-scripts/gather_db
- collection-scripts/gather_run
This patch introduces the ability to specify an environment variable with a list of `openstack` databases that should be dumped. It is also possible to set the variable to `ALL`, which results in trigger the `mysqldump` command with the `--all-databases` option. By default the `OPENSTACK_DATABASES` variables is `unset` and this flow is entirely skipped. 
To enable it, the aforementioned variable should be explicitly set.
> Optionally dump the openstack databases

- collection-scripts/gather_services_status
Adds service data collection for ironic. Does not add a GMR status retriever as GMR is *entirely* optional for ironic and is only a suggested dependency for the RPM packaging.
> OSPRH-1435: add must-gather support for ironic

- collection-scripts/gather_services_status
This adds openstack * list commands for telemetry services. I also replaced a few tabs I found in the file.
> Gather telemetry services statuses

- README.md
- collection-scripts/gather_secrets
- pyscripts/mask.py
- pyscripts/test_mask.py
- pyscripts/tests/samples/secret3.yaml
This patch adds the ability to detect a `.conf` file within a `Secret` and dump its content in the current directory.
This helps to ease the _troubleshooting_ when looking for a service config file: instead of `base64 -d` a portion of the `Secret`, we provide a dump of that file in the form `<secret.yaml>-<config_file_name>.conf` within the same directory.
For CI only purposes, there are situations where is required to look at connection strings, username and passwords generated in the operators context. For this reason a `DO_NOT_MASK` environment variable is provided to entirely bypass (in CI) the masking mechanism.
Implements: [OSPRH-726](https://issues.redhat.com/browse/OSPRH-726)
> Add dump-conf option to the mask secret script

- collection-scripts/gather_services_status
The command syntax is "baremetal port group list". not "baremetal portgroup list".
> Fix ironic portgroup list

- collection-scripts/gather_ctlplane_resources
The current script tries to get the `NetworkAttachmentDefinition` using the `nad` keyword, but that doesn't exist on the OCP cluster.
Using keyword `NetworkAttachmentDefinition` doesn't work either, only using `network-attachment-definition` or
`network-attachment-definitions` works.
This patch changes to using the plural version that works.
> Get NetworkAttachmentDefinition objects

- collection-scripts/gather_services_status
Patch adds some basic data collection of octavia resources. Missing is some extra detail dumps that involve looping over output of previous commands.
> Add some basic collection for octavia service details

- collection-scripts/gather_ctlplane_resources
https://logserver.rdoproject.org/47/47/67bc7d39d5f268d35c6e2e3184e8a89b7e64da10/github-check/podified-multinode-edpm-deployment-crc/76e3cad/controller/ci-framework-data/logs/quay-rdoproject-org-openstack-k8s-operators-openstack-must-gather-sha256-adfecf98bc58627d20b87c9e4f29a9b97dfce40bf0cfebb4a32e789c3caed8fb/namespaces/openstack/events.log
> Sort events by timestamp

- collection-scripts/gather_edpm_sos
If in the `openstackdataplanenodesets` resources the `$node.ansible.ansibleHost` is not defined, the must-gather from the compute nodes fails with this kind of error:
```
[must-gather-27lcm] POD 2024-04-26T22:51:13.104464074Z /usr/bin/bg.sh: eval: line 30: syntax error near unexpected token `('
[must-gather-27lcm] POD 2024-04-26T22:51:13.104464074Z /usr/bin/bg.sh: eval: line 30: `gather_edpm_sos compute-0 %!s(<nil>) zuul dataplane-ansible-ssh-private-key-secret openstack'
[must-gather-27lcm] POD 2024-04-26T22:51:13.104464074Z /usr/bin/bg.sh: eval: line 30: syntax error near unexpected token `('
[must-gather-27lcm] POD 2024-04-26T22:51:13.104464074Z /usr/bin/bg.sh: eval: line 30: `gather_edpm_sos compute-1 %!s(<nil>) zuul dataplane-ansible-ssh-private-key-secret openstack' …
```
> Use `$node.hostName` if `$node.ansible.ansibleHost` isn't available

- collection-scripts/gather_edpm_sos
The container and openstack profiles should be gathered by default.
Jira: https://issues.redhat.com/browse/OSPRH-7135
Signed-off-by: James Slagle <jslagle@redhat.com>
> Add container and openstack profiles to gather_edpm_sos

- Dockerfile
- collection-scripts/gather_edpm_sos
This patch is a followup of #49 since we can't ssh to $hostname from must-gather container because it doesn't have access to OSP controlplane DNS server.
To enhance readability and maintainability of the script, acquiring the required parameters in the $data variable was changed from go-template to json, using jq command as its parser.
An updated Dockerfile was provided to install jq in the must-gather image.
> Use controlplane ip from compute nodes instead of hostname for gathering the sosreport logs

- collection-scripts/common.sh
- collection-scripts/gather_crs
This are mainly resources in the openshift-logging and openshift-operators-redhat namespaces.
> Gather telemetry logging related resources

- collection-scripts/gather_edpm_sos
- collection-scripts/gather_sos
Having decompressed sos reports is breaking the Zuul web interface for users, due to how Zuul works the front end downloads a manifest file and uses that to generate the artifacts and logs tab for the build.
Out jobs are creating 20mb+ manifest files and these need to be downloaded and processed. The file size isn't the main issue, the file count in the manifest file causes high processing and is locking up users browsers.
Just stopping the compression on sos reports halves the file count in the manifest file.
Jira: https://issues.redhat.com/browse/OSPRH-7521
> Update gather_sos* to not decompress collected sos reports

- collection-scripts/gather_ctlplane_resources
- collection-scripts/gather_run
- collection-scripts/gather_sos
Current must gather only gathers the logs in the pod's current log file
and the previous container run, so once the logs are rotated we no
longer have access to that information through the `oc` command and that
information is not present in the must gather tar.xz.
Rotated logs are only available under `/var/log/pods` and, since log
rotation is not an OpenShift responsibility, there is no way to get them
besides accessing that directory.
There is no sos plugin that gathers the contents of `/var/log/pods` only
for `/var/log/containers`, but in this last directory there are only
symlinks to the last files, not the rotated ones.
I see 3 ways to solve this issue:
- Submit a PR to upstream SOS report repository with a new plugin to
gather that directory. This would take time and we would need …
> SOS Report: Get rotated container logs

- collection-scripts/gather_edpm_sos
When we are downloading the SOS reports from EDPM nodes, the whole tar data is shown in stdout, making them a mess.
In this patch we change how we get the SOS from the nodes, and instead of using `tee`, we redirect stdout to the file and stderr to stdout, so we still see any errors on the download but we no longer have to see the whole tar in stdout.
> Cleaner logs on EDPM SOS reports

- collection-scripts/gather_sos
Some tar versions return exit code 1 on warnings such as file changed during read, other return exit code 0.
With this patch the tar command run used to gather /var/log/pods will only be considered failed if the exit code is 2 or greater.
> Fix pod log gathering

- collection-scripts/gather_edpm_sos
The must-gather failed to collect SOS reports from more than CONCURRENCY
nodes. It is caused by ssh reading the stdin and consuming data used by
the outer loop iterating over the nodes to be collected from.
Added -n to ssh to avoid stdin stealing.
> Fix missing EDPM SOS reports

- README.md
- collection-scripts/gather_edpm_sos
- collection-scripts/gather_sos
The `openstack_edpm` plugin was being gathered on the OCP cluster nodes, but it's intended for the EDPM nodes, so we remove it from the list of plugins in `SOS_ONLY_PLUGINS`.
We move the `openstack_edpm` to the EDPM sos gathering script replacing the old `openstack` profile that is not as appropriate for openstack-operator deployments.
> [SOS EDPM] Use openstack_edpm profile

- README.md
- collection-scripts/common.sh
- collection-scripts/gather_ctlplane_resources
- collection-scripts/gather_db
- collection-scripts/gather_edpm_sos
- collection-scripts/gather_run
- collection-scripts/gather_services_status
- collection-scripts/gather_sos
- collection-scripts/gather_trigger_gmr
This PR improves the log gathering in the following way:
- Make services and operator namespaces configurable instead of statically set to `openstack` and `openstack-operators`
- Go back to retrieving the logs via the OpenShift API
- Only get rotated logs in SOS gathering
- Fix gathering not waiting for background tasks!!
- Create symlinks to rotated logs
> Fix container logs

- collection-scripts/gather_trigger_gmr
When gathering data we can see the following error
```
/usr/bin/bg.sh: line 30: none: No such file or directory
```
This is caused by the `gather_trigger_gmr` trying to run in the background the following command:
```
/usr/bin/oc -n openstack  exec  cinder-db-purge-28654561-hx97v   -c   <none> -- touch /etc/cinder
```
This patch makes it so that the code no longer tries to trigger GMR on pods that are not cinder services (these pods have the component label set).
> Cinder GMR triggering

- collection-scripts/gather_ctlplane_resources
This patch fixes the current issue related to the fact that we try to get logs from pods that are not present in the namespace. This is caused by the fact that the `crash_status` variable is sometimes not predictable and an output made by many strings is produced. We only need to know if the `Pod` was terminated, and get the `-previous` log, but we don't care about the reason of the crash. In addition, given the complexity generated by `go-template`, we moved the data processing to `json` and `jq`, as it results easy to read and maintain.
Jira: [OSPRH-8197](https://issues.redhat.com/browse/OSPRH-8197)
> Do not try to get logs from non existent pods

- collection-scripts/gather_sos
Add the `crypto` plugin to the list of plugins gathered by the SOS report on the OCP nodes.
This is necessary for example to gather FIPS enabled status on the nodes.
There's no need to do anything for EDPM nodes because we gather the `system` profile there and the `crypto` plugin is part of that profile.
> SOS OCP: Add crypto plugin

- collection-scripts/gather_ctlplane_resources
If a pod is in Pending state and has no 'status.containerStatus' field,
the jq command crashes, and we get no logs. This change sets the
container name for those pods as null, and then we can skip collecting
logs for that pod, while still calling 'oc describe' on it.
> Skip collecting logs from pods if they are pending

- collection-scripts/gather_services_status
This patch set's up the glance directory for service info gathering.
It also adds the task list which tells us about the status of import operations.
Future work:
In future, it would be useful to add stores info which tells us about configured
backends and their properties but it is not currently available in openstackclient.
> Gather glance task information

- README.md
- collection-scripts/gather_run
This patch adds a step at the end of the gathering to produce an
additional single archive of the whole gathered content.
Use case: I need to grep across pod logs with a request ID so I need to
download the content of the gathering. However the content is
in a lot of small files causing that a recursive wget takes tens of
minutes to finish and probably generates excess load on the log server.
* COMPRESSED_PATH env var can be used to define where to store the
archive created. By default the archive is stored in the root of
the gather directory
* DELETE_AFTER_COMPRESSION env var can be used to define whether the
uncompressed files are deleted after the compression is done. By
default the uncompressed files are also kept. If DELETE_AFTER_COMPRESSION
is set to 1 then the files are deleted.
> Produce a single archive

- OWNERS
- OWNERS_ALIASES
Merge the original list of project approvers with the larger openstack approvers list and adds juliakreger to approvers list.
> Merge mustgather-approvers group into openstack-approvers

- collection-scripts/gather_ctlplane_resources
When doing the request for pods in the namespace, set init = true when the pod have init containers. When collecting pod logs make another request for the pods initcontainers and collect their logs.
> Collect init container logs

- collection-scripts/gather_services_status
This patch adds some basic data collection of designate resources.
> Add some basic collection for designate service details

- collection-scripts/gather_run
- collection-scripts/gather_version
This is in align with must-gather guidelines [1] and will much easier to discover automatically archive data context by the insights and ocp_ccx plugin.
[1] https://github.com/openshift/must-gather/blob/master/must-gather.md#must-gather-images
Related: #[OSPRH-11237](https://issues.redhat.com//browse/OSPRH-11237)
Closes: #[OSPRH-13336](https://issues.redhat.com//browse/OSPRH-13336)
> Add version file to the data collected with openstack-must-gather

- Dockerfile
- Makefile
- README.md
As per the guidelines [1], a `must-gather` image must produce a `version` file that indicates the **product** and the **version**, following the `major.minor.micro.qualifier` approach. By doing this is possible to integrate it with other tools that need this information to process the associated data.
Patch [2] produces a `version` file as part of the `must-gather` execution, while here both the `Makefile` and the `Containerfile` are modified to support this new `ENV` var.
Version is produced in the form `<branch>-<commit_count>-g<commit>`, because as per the `openstack-k8s-operators` branching model tags are not used to indentify a particular release.
Related: #[OSPRH-11237](https://issues.redhat.com//browse/OSPRH-11237)
Related: …
> Add OS_GIT_VERSION to the openstack-must-gather build system

- pyscripts/mask.py
Current issues:
- `ssh-privatekey` under data was not under the scope of masking.
- last-applied-configuration which is under `metadata` was also not under the scope of masking.
This PR aims to fix both issues. A new `_applyMask` method is added to do recursive call over secrets which are part of `metadata`.
Testing:
Currently, the python script was directly tested against a k8s secret dump and it was able to mask `ssh-privatekey` within `data` and `metadata`. It has not been tested as a part of a job.
> Patch ssh private key secret

- collection-scripts/gather_secrets
Gather any NodeSet related secrets, based on the NodeSet name. This
would include the generated inventory as well as the network-data and
user-data secrets that are generated from the OpenStackBaremetalSet for
baremetal provisioning.
Signed-off-by: James Slagle <jslagle@redhat.com>
> Gather NodeSet related secrets

- collection-scripts/common.sh
Other than `buildConfig`, `imageStream` objects are relevant in many use cases (e.g. `hotfix` process). This patch adds this new entity that should be retrieved as part of the `must-gather` execution.
Jira: https://issues.redhat.com/browse/OSPRH-15934
> Gather imagestream as part of the process

- README.md
- collection-scripts/gather_sos
In disconnected environments it might happen that we're not able to reach the `support-tools` default public registry. With this patch we add an environment variable to customize the support-tools container image and point to an arbitrary mirror.
> Customize support-tools image for disconnected environments

- collection-scripts/common.sh
- collection-scripts/gather_services_status
For the support team is useful to gather information about existing rabbitmq clusters.
This patch adds support to gather this information as part of a regular gather_services status execution.
Jira: https://issues.redhat.com/browse/OSPRH-16331
> Add rabbitmq info outputs in must-gather

- collection-scripts/gather_services_status
The designate-manage pool show_config output will be helpful with debugging Designate future failures.
This commit adds it to openstack-must-gather.
Note: this commit does not include the --all_pools flag in the commit. We should add it once openstackclient pod has access to it.
> Add designate-manage pool show_config output

- collection-scripts/gather_network
A `NodeNetworkState` object exists on every node in the cluster. This object is periodically updated and captures the state of the network for that node.
This patch updates the `gather_network` script and adds `nns` to the list of captured resources.
It also fixes a small issue in the other `oc` calls to prevent an empty line being printed.
Jira: https://issues.redhat.com/browse/OSPRH-16785
> Collect NodeNetworkState

- collection-scripts/gather_services_status
Until today we had some incorrect Designate cli commands on the must gather collection script (incorrect format and scope).
This patch removes and fixes the incorrect commands.
> Fix Designate must gather collection script

- collection-scripts/gather_services_status
"openstack network agent list" output is collected twice: first one is placed in ctlplane/ folder, another one in ctlplane/neutron folder. This patch removes the first output collection.
> Remove duplicate network agent list command

- collection-scripts/gather_trigger_gmr
With patch [1] the path used by `oslo_reports` to trigger `cinder` `gmr` has been updated.
This patch reflects the change provided in the cinder-operator that is caused by the root removal patch series.
[1] https://github.com/openstack-k8s-operators/cinder-operator/pull/544
Jira: https://issues.redhat.com/browse/OSPRH-17882
> Update cinder gmr path

- collection-scripts/gather_trigger_gmr
As we've done for `nova` and `cinder`, this patch adds a function that triggers manila `GMR`. This is useful when troubleshooting or when we request additional information for customer cases.
Jira: https://issues.redhat.com/browse/OSPRH-19720
> Trigger manila GMR

- collection-scripts/gather_sos
Add firewall related collection to the sos reports.  Firewall rules can reflect the behaviour of OpenShift Services + the CNI plugin. What appears here will be dependent on the OpenShift version.
> Add firewall stuff to sosreports.
